name: Deployment

on:
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build and deploy to itch.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Unity Activation
      - name: Activate Unity license
        uses: webbertakken/unity-activate@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.14f1
          targetPlatform: WebGL

      # Publish to itch.io
      - name: Deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: clicknrun
          ITCH_USER: yayo-acosta
          PACKAGE: build
          VERSION: 0.0.4
